# Generated by Django 2.2.5 on 2019-10-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '상품', 'verbose_name_plural': '상품들'},
        ),
        migrations.AlterModelTable(
            name='shop',
            table='trackline_shop',
        ),
    ]
