# Generated by Django 2.2.5 on 2019-10-08 16:49

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191008_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='photo',
            field=models.ImageField(upload_to=shop.models.Shop.date_upload_to),
        ),
    ]
